title:             mkki world
email:             gosorn1@gmail.com
description:      dev_mkki
author:            Start Bootstrap
baseurl:           ""
url:               "http://mkki.github.io"

# Social Profiles
twitter_username:
github_username:   mkki
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
